// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA65Elh1qpeYb-WZ5sp0YMbvJwSwyN4Iko',
    appId: '1:789661720511:web:98bc3228104982dda8cb0a',
    messagingSenderId: '789661720511',
    projectId: 'social-media-app-fe12e',
    authDomain: 'social-media-app-fe12e.firebaseapp.com',
    storageBucket: 'social-media-app-fe12e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3O-Bl9ML6YsWmYEyH1HT8piparBihVTk',
    appId: '1:789661720511:android:960e038e795ead10a8cb0a',
    messagingSenderId: '789661720511',
    projectId: 'social-media-app-fe12e',
    storageBucket: 'social-media-app-fe12e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7dWPjKQVjTyAjKeRJfnHo0ubyk-H7w64',
    appId: '1:789661720511:ios:65f341e048c9c256a8cb0a',
    messagingSenderId: '789661720511',
    projectId: 'social-media-app-fe12e',
    storageBucket: 'social-media-app-fe12e.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7dWPjKQVjTyAjKeRJfnHo0ubyk-H7w64',
    appId: '1:789661720511:ios:65f341e048c9c256a8cb0a',
    messagingSenderId: '789661720511',
    projectId: 'social-media-app-fe12e',
    storageBucket: 'social-media-app-fe12e.firebasestorage.app',
    iosBundleId: 'com.example.socialMediaApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA65Elh1qpeYb-WZ5sp0YMbvJwSwyN4Iko',
    appId: '1:789661720511:web:fbbac1ffbe78d1bea8cb0a',
    messagingSenderId: '789661720511',
    projectId: 'social-media-app-fe12e',
    authDomain: 'social-media-app-fe12e.firebaseapp.com',
    storageBucket: 'social-media-app-fe12e.firebasestorage.app',
  );
}
